// Define a class for the NFT data
class RWAData {
  final String id;
  final String symbol;
  final num price;
  final String image;

  RWAData(
      {required this.id,
      required this.symbol,
      required this.price,
      required this.image});
}

// Create a list of mock data
List<RWAData> mockRWAData = [
  RWAData(id: "1", symbol: "STG", price: 0.00, image: "1.png"),
  RWAData(id: "2", symbol: "KHPN", price: 0.00, image: "2.png"),
  RWAData(id: "3", symbol: "INR", price: 0.00, image: "3.png"),
  RWAData(id: "4", symbol: "SAY", price: 0.00, image: "4.png"),
  RWAData(id: "5", symbol: "KPP", price: 0.00, image: "5.png"),
  RWAData(id: "6", symbol: "FNG", price: 0.00, image: "6.png"),
  RWAData(id: "7", symbol: "PAI", price: 0.00, image: "7.png"),
  RWAData(id: "8", symbol: "TBM", price: 0.00, image: "8.png"),
  RWAData(id: "9", symbol: "FTD", price: 0.00, image: "9.png"),
  RWAData(id: "10", symbol: "NKP", price: 0.00, image: "10.png"),
  RWAData(id: "11", symbol: "TLN", price: 0.00, image: "11.png"),
  RWAData(id: "12", symbol: "ATN", price: 0.00, image: "12.png"),
  RWAData(id: "13", symbol: "NTN", price: 0.00, image: "13.png"),
  RWAData(id: "14", symbol: "SSD", price: 0.00, image: "14.png"),
  RWAData(id: "15", symbol: "RMK", price: 0.00, image: "15.png"),
  RWAData(id: "16", symbol: "SVYP", price: 0.00, image: "16.png"),
  RWAData(id: "17", symbol: "BTAD", price: 0.00, image: "17.png"),
  RWAData(id: "18", symbol: "SRJ", price: 0.00, image: "18.png"),
  RWAData(id: "19", symbol: "SID", price: 0.00, image: "19.png"),
  RWAData(id: "20", symbol: "SWC", price: 0.00, image: "20.png"),
  RWAData(id: "21", symbol: "THC", price: 0.00, image: "21.png"),
  RWAData(id: "22", symbol: "MNY", price: 0.00, image: "22.png"),
  RWAData(id: "23", symbol: "MHT", price: 0.00, image: "23.png"),
  RWAData(id: "24", symbol: "SDS", price: 0.00, image: "24.png"),
  RWAData(id: "25", symbol: "RSR", price: 0.00, image: "25.png"),
  RWAData(id: "26", symbol: "RRU", price: 0.00, image: "26.png"),
  RWAData(id: "27", symbol: "MND", price: 0.00, image: "27.png"),
  RWAData(id: "28", symbol: "TND", price: 0.00, image: "28.png"),
  RWAData(id: "29", symbol: "SND", price: 0.00, image: "29.png"),
  RWAData(id: "30", symbol: "MKD", price: 0.00, image: "30.png"),
  RWAData(id: "31", symbol: "MID", price: 0.00, image: "31.png"),
  RWAData(id: "32", symbol: "RED", price: 0.00, image: "32.png"),
  RWAData(id: "33", symbol: "PLID", price: 0.00, image: "33.png"),
  RWAData(id: "34", symbol: "PLOD", price: 0.00, image: "34.png"),
  RWAData(id: "35", symbol: "GMD", price: 0.00, image: "35.png"),
  RWAData(id: "36", symbol: "TLD", price: 0.00, image: "36.png"),
  RWAData(id: "37", symbol: "SGD", price: 0.00, image: "37.png"),
  RWAData(id: "38", symbol: "CGD", price: 0.00, image: "38.png"),
  RWAData(id: "39", symbol: "BIAD", price: 0.00, image: "39.png"),
  RWAData(id: "40", symbol: "CHGD", price: 0.00, image: "40.png"),
  RWAData(id: "41", symbol: "PKD", price: 0.00, image: "41.png"),
  RWAData(id: "42", symbol: "VYD", price: 0.00, image: "42.png"),
  RWAData(id: "43", symbol: "SKD", price: 0.00, image: "43.png"),
  RWAData(id: "44", symbol: "SATI", price: 0.00, image: "44.png"),
  RWAData(id: "45", symbol: "SAB", price: 0.00, image: "45.png"),
  RWAData(id: "46", symbol: "YIM", price: 0.00, image: "46.png"),
  RWAData(id: "47", symbol: "PYKT", price: 0.00, image: "47.png"),
  RWAData(id: "48", symbol: "HMID", price: 0.00, image: "48.png"),
  RWAData(id: "49", symbol: "PTN", price: 0.00, image: "49.png"),
  RWAData(id: "50", symbol: "SBD", price: 0.00, image: "50.png"),
  RWAData(id: "51", symbol: "ATID", price: 0.00, image: "51.png"),
  RWAData(id: "52", symbol: "CHD", price: 0.00, image: "52.png"),
  RWAData(id: "53", symbol: "PPD", price: 0.00, image: "53.png"),
  RWAData(id: "54", symbol: "SVLD", price: 0.00, image: "54.png"),
  RWAData(id: "55", symbol: "HRD", price: 0.00, image: "55.png"),
  RWAData(id: "56", symbol: "PYD", price: 0.00, image: "56.png"),
  RWAData(id: "57", symbol: "THKD", price: 0.00, image: "57.png"),
  RWAData(id: "58", symbol: "TDD", price: 0.00, image: "58.png"),
  RWAData(id: "59", symbol: "TKD", price: 0.00, image: "59.png"),
  RWAData(id: "60", symbol: "AYC", price: 0.00, image: "60.png"),
  RWAData(id: "61", symbol: "SUVC", price: 0.00, image: "61.png"),
  RWAData(id: "62", symbol: "PMJC", price: 0.00, image: "62.png"),
  RWAData(id: "63", symbol: "CCC", price: 0.00, image: "63.png"),
  RWAData(id: "64", symbol: "JWC", price: 0.00, image: "64.png"),
  RWAData(id: "65", symbol: "PHT", price: 0.00, image: "65.png"),
  RWAData(id: "66", symbol: "PNC", price: 0.00, image: "66.png"),
  RWAData(id: "67", symbol: "PODC", price: 0.00, image: "67.png"),
  RWAData(id: "68", symbol: "CHPC", price: 0.00, image: "68.png"),
  RWAData(id: "69", symbol: "RPC", price: 0.00, image: "69.png"),
  RWAData(id: "70", symbol: "KPC", price: 0.00, image: "70.png"),
  RWAData(id: "71", symbol: "PRC", price: 0.00, image: "71.png"),
  RWAData(id: "72", symbol: "PMC", price: 0.00, image: "72.png"),
  RWAData(id: "73", symbol: "MKC", price: 0.00, image: "73.png"),
  RWAData(id: "74", symbol: "YNG", price: 0.00, image: "74.png"),
  RWAData(id: "75", symbol: "OMC", price: 0.00, image: "75.png"),
  RWAData(id: "76", symbol: "TTC", price: 0.00, image: "76.png"),
  RWAData(id: "77", symbol: "RYC", price: 0.00, image: "77.png"),
  RWAData(id: "78", symbol: "DNC", price: 0.00, image: "78.png"),
  RWAData(id: "79", symbol: "PDC", price: 0.00, image: "79.png"),
  RWAData(id: "80", symbol: "PPDC", price: 0.00, image: "80.png"),
  RWAData(id: "81", symbol: "TYC", price: 0.00, image: "81.png"),
  RWAData(id: "82", symbol: "PKSC", price: 0.00, image: "82.png"),
  RWAData(id: "83", symbol: "RCWC", price: 0.00, image: "83.png"),
  RWAData(id: "84", symbol: "SSMC", price: 0.00, image: "84.png"),
  RWAData(id: "85", symbol: "SMNC", price: 0.00, image: "85.png"),
  RWAData(id: "86", symbol: "SISPC", price: 0.00, image: "86.png"),
  RWAData(id: "87", symbol: "SWTC", price: 0.00, image: "87.png"),
  RWAData(id: "88", symbol: "TWEC", price: 0.00, image: "88.png"),
  RWAData(id: "89", symbol: "STWC", price: 0.00, image: "89.png"),
  RWAData(id: "90", symbol: "CHGPC", price: 0.00, image: "90.png"),
  RWAData(id: "91", symbol: "MDC", price: 0.00, image: "91.png"),
  RWAData(id: "92", symbol: "TKC", price: 0.00, image: "92.png"),
  RWAData(id: "93", symbol: "IPC", price: 0.00, image: "93.png"),
  RWAData(id: "94", symbol: "KWC", price: 0.00, image: "94.png"),
  RWAData(id: "95", symbol: "LOSC", price: 0.00, image: "95.png"),
  RWAData(id: "96", symbol: "SFC", price: 0.00, image: "96.png"),
  RWAData(id: "97", symbol: "DINC", price: 0.00, image: "97.png"),
  RWAData(id: "98", symbol: "SNUC", price: 0.00, image: "98.png"),
  RWAData(id: "99", symbol: "SFAC", price: 0.00, image: "99.png"),
  RWAData(id: "100", symbol: "UDSC", price: 0.00, image: "100.png"),
  RWAData(id: "101", symbol: "PLNGC", price: 0.00, image: "101.png"),
  RWAData(id: "102", symbol: "CRRRC", price: 0.00, image: "102.png"),
];
